import 'package:flutter/foundation.dart';
import 'package:pronounce_it_right/model/word_model.dart';

class WordsProvider with ChangeNotifier {
  List<Word> _words = [];
  String _selectedCategory = 'All';
  String _difficulty = 'All';

  List<Word> get words => _filterWords();
  String get selectedCategory => _selectedCategory;
  String get difficulty => _difficulty;

  WordsProvider() {
    _loadWords();
  }

  void _loadWords() {
    // Initial word list
    _words = [
      Word(
        id: '1',
        french: 'chat',
        english: 'cat',
        category: 'Animals',
        difficulty: 'Easy',
        phoneticHint: 'sha (like "shah" but shorter)',
      ),
      Word(
        id: '2',
        french: 'chien',
        english: 'dog',
        category: 'Animals',
        difficulty: 'Easy',
        phoneticHint: 'shi-en (nasal "en" sound)',
      ),
      Word(
        id: '3',
        french: 'maison',
        english: 'house',
        category: 'Objects',
        difficulty: 'Easy',
        phoneticHint: 'may-zon (nasal "on" sound)',
      ),
      Word(
        id: '4',
        french: 'grenouille',
        english: 'frog',
        category: 'Animals',
        difficulty: 'Medium',
        phoneticHint: 'gruh-noo-yuh (soft "r", "oo" as in "book")',
      ),
      Word(
        id: '5',
        french: 'voiture',
        english: 'car',
        category: 'Transport',
        difficulty: 'Easy',
      ),
      Word(
        id: '6',
        french: 'pomme',
        english: 'apple',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '7',
        french: 'cheval',
        english: 'horse',
        category: 'Animals',
        difficulty: 'Medium',
      ),
      Word(
        id: '8',
        french: 'livre',
        english: 'book',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '9',
        french: 'chaise',
        english: 'chair',
        category: 'Furniture',
        difficulty: 'Easy',
      ),
      Word(
        id: '10',
        french: 'arbre',
        english: 'tree',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '11',
        french: 'poisson',
        english: 'fish',
        category: 'Animals',
        difficulty: 'Medium',
      ),
      Word(
        id: '12',
        french: 'oiseau',
        english: 'bird',
        category: 'Animals',
        difficulty: 'Medium',
      ),
      Word(
        id: '13',
        french: 'soleil',
        english: 'sun',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '14',
        french: 'lune',
        english: 'moon',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '15',
        french: 'étoile',
        english: 'star',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '16',
        french: 'ordinateur',
        english: 'computer',
        category: 'Technology',
        difficulty: 'Medium',
      ),
      Word(
        id: '17',
        french: 'téléphone',
        english: 'phone',
        category: 'Technology',
        difficulty: 'Easy',
      ),
      Word(
        id: '18',
        french: 'porte',
        english: 'door',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '19',
        french: 'fenêtre',
        english: 'window',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '20',
        french: 'chaussure',
        english: 'shoe',
        category: 'Clothing',
        difficulty: 'Medium',
      ),
      Word(
        id: '21',
        french: 'chemise',
        english: 'shirt',
        category: 'Clothing',
        difficulty: 'Medium',
      ),
      Word(
        id: '22',
        french: 'pantalon',
        english: 'pants',
        category: 'Clothing',
        difficulty: 'Medium',
      ),
      Word(
        id: '23',
        french: 'stylo',
        english: 'pen',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '24',
        french: 'papier',
        english: 'paper',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '25',
        french: 'bureau',
        english: 'desk',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '26',
        french: 'lampe',
        english: 'lamp',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '27',
        french: 'vélo',
        english: 'bicycle',
        category: 'Transport',
        difficulty: 'Easy',
      ),
      Word(
        id: '28',
        french: 'camion',
        english: 'truck',
        category: 'Transport',
        difficulty: 'Medium',
      ),
      Word(
        id: '29',
        french: 'train',
        english: 'train',
        category: 'Transport',
        difficulty: 'Medium',
      ),
      Word(
        id: '30',
        french: 'avion',
        english: 'plane',
        category: 'Transport',
        difficulty: 'Medium',
      ),
      Word(
        id: '31',
        french: 'pain',
        english: 'bread',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '32',
        french: 'fromage',
        english: 'cheese',
        category: 'Food',
        difficulty: 'Medium',
      ),
      Word(
        id: '33',
        french: 'eau',
        english: 'water',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '34',
        french: 'lait',
        english: 'milk',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '35',
        french: 'banane',
        english: 'banana',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '36',
        french: 'orange',
        english: 'orange',
        category: 'Food',
        difficulty: 'Easy',
      ),
      Word(
        id: '37',
        french: 'cerise',
        english: 'cherry',
        category: 'Food',
        difficulty: 'Medium',
      ),
      Word(
        id: '38',
        french: 'fraise',
        english: 'strawberry',
        category: 'Food',
        difficulty: 'Medium',
      ),
      Word(
        id: '39',
        french: 'légume',
        english: 'vegetable',
        category: 'Food',
        difficulty: 'Medium',
      ),
      Word(
        id: '40',
        french: 'salade',
        english: 'salad',
        category: 'Food',
        difficulty: 'Medium',
      ),
      Word(
        id: '41',
        french: 'montagne',
        english: 'mountain',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '42',
        french: 'rivière',
        english: 'river',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '43',
        french: 'forêt',
        english: 'forest',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '44',
        french: 'mer',
        english: 'sea',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '45',
        french: 'océan',
        english: 'ocean',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '46',
        french: 'neige',
        english: 'snow',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '47',
        french: 'pluie',
        english: 'rain',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '48',
        french: 'vent',
        english: 'wind',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '49',
        french: 'orage',
        english: 'storm',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '50',
        french: 'éclair',
        english: 'lightning',
        category: 'Nature',
        difficulty: 'Hard',
        phoneticHint: 'ay-clair (emphasis on "clair")',
      ),
      Word(
        id: '51',
        french: 'tonnerre',
        english: 'thunder',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '52',
        french: 'tempête',
        english: 'storm',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '53',
        french: 'arc-en-ciel',
        english: 'rainbow',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '54',
        french: 'glace',
        english: 'ice',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '55',
        french: 'bouteille',
        english: 'bottle',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '56',
        french: 'couteau',
        english: 'knife',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '57',
        french: 'fourchette',
        english: 'fork',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '58',
        french: 'cuillère',
        english: 'spoon',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '59',
        french: 'assiette',
        english: 'plate',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '60',
        french: 'verre',
        english: 'glass',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '61',
        french: 'serviette',
        english: 'napkin',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '62',
        french: 'table',
        english: 'table',
        category: 'Furniture',
        difficulty: 'Easy',
      ),
      Word(
        id: '63',
        french: 'lit',
        english: 'bed',
        category: 'Furniture',
        difficulty: 'Easy',
      ),
      Word(
        id: '64',
        french: 'oreiller',
        english: 'pillow',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '65',
        french: 'couverture',
        english: 'blanket',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '66',
        french: 'rideau',
        english: 'curtain',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '67',
        french: 'tapis',
        english: 'carpet',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '68',
        french: 'miroir',
        english: 'mirror',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '69',
        french: 'étagère',
        english: 'shelf',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '70',
        french: 'placard',
        english: 'closet',
        category: 'Furniture',
        difficulty: 'Medium',
      ),
      Word(
        id: '71',
        french: 'brosse',
        english: 'brush',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '72',
        french: 'savon',
        english: 'soap',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '73',
        french: 'shampoing',
        english: 'shampoo',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '74',
        french: 'dentifrice',
        english: 'toothpaste',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '75',
        french: 'serviette de bain',
        english: 'bath towel',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '76',
        french: 'toilettes',
        english: 'toilet',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '77',
        french: 'douche',
        english: 'shower',
        category: 'Objects',
        difficulty: 'Easy',
      ),
      Word(
        id: '78',
        french: 'lavabo',
        english: 'sink',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '79',
        french: 'réfrigérateur',
        english: 'refrigerator',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '80',
        french: 'congélateur',
        english: 'freezer',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '81',
        french: 'cuisinière',
        english: 'stove',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '82',
        french: 'four',
        english: 'oven',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '83',
        french: 'micro-ondes',
        english: 'microwave',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '84',
        french: 'grille-pain',
        english: 'toaster',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '85',
        french: 'bouilloire',
        english: 'kettle',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '86',
        french: 'mixeur',
        english: 'blender',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '87',
        french: 'aspirateur',
        english: 'vacuum cleaner',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '88',
        french: 'balai',
        english: 'broom',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '89',
        french: 'seau',
        english: 'bucket',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '90',
        french: 'éponge',
        english: 'sponge',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '91',
        french: 'détergent',
        english: 'detergent',
        category: 'Objects',
        difficulty: 'Hard',
      ),
      Word(
        id: '92',
        french: 'poubelle',
        english: 'trash can',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '93',
        french: 'balcon',
        english: 'balcony',
        category: 'Objects',
        difficulty: 'Medium',
      ),
      Word(
        id: '94',
        french: 'jardin',
        english: 'garden',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '95',
        french: 'plante',
        english: 'plant',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '96',
        french: 'fleur',
        english: 'flower',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '97',
        french: 'feuille',
        english: 'leaf',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '98',
        french: 'gazon',
        english: 'grass',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '99',
        french: 'terre',
        english: 'soil',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '100',
        french: 'caillou',
        english: 'pebble',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '101',
        french: 'rocher',
        english: 'rock',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '102',
        french: 'montagne',
        english: 'mountain',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '103',
        french: 'colline',
        english: 'hill',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '104',
        french: 'vallée',
        english: 'valley',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '105',
        french: 'plaine',
        english: 'plain',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '106',
        french: 'forêt',
        english: 'forest',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '107',
        french: 'jungle',
        english: 'jungle',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '108',
        french: 'désert',
        english: 'desert',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '109',
        french: 'rivière',
        english: 'river',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '110',
        french: 'lac',
        english: 'lake',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '111',
        french: 'océan',
        english: 'ocean',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '112',
        french: 'mer',
        english: 'sea',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '113',
        french: 'plage',
        english: 'beach',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '114',
        french: 'coquillage',
        english: 'seashell',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '115',
        french: 'sable',
        english: 'sand',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '116',
        french: 'volcan',
        english: 'volcano',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '117',
        french: 'lave',
        english: 'lava',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '118',
        french: 'cratère',
        english: 'crater',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '119',
        french: 'paysage',
        english: 'landscape',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '120',
        french: 'ciel',
        english: 'sky',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '121',
        french: 'étoile',
        english: 'star',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '122',
        french: 'lune',
        english: 'moon',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '123',
        french: 'soleil',
        english: 'sun',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '124',
        french: 'nuage',
        english: 'cloud',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '125',
        french: 'pluie',
        english: 'rain',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '126',
        french: 'neige',
        english: 'snow',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '127',
        french: 'grêle',
        english: 'hail',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '128',
        french: 'brouillard',
        english: 'fog',
        category: 'Nature',
        difficulty: 'Medium',
      ),
      Word(
        id: '129',
        french: 'vent',
        english: 'wind',
        category: 'Nature',
        difficulty: 'Easy',
      ),
      Word(
        id: '130',
        french: 'ouragan',
        english: 'hurricane',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '131',
        french: 'tremblement de terre',
        english: 'earthquake',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '132',
        french: 'inondation',
        english: 'flood',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '133',
        french: 'feu de forêt',
        english: 'wildfire',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '134',
        french: 'sécheresse',
        english: 'drought',
        category: 'Nature',
        difficulty: 'Hard',
      ),
      Word(
        id: '135',
        french: 'pollution',
        english: 'pollution',
        category: 'Environment',
        difficulty: 'Medium',
      ),
      Word(
        id: '136',
        french: 'recyclage',
        english: 'recycling',
        category: 'Environment',
        difficulty: 'Medium',
      ),
      Word(
        id: '137',
        french: 'déchet',
        english: 'waste',
        category: 'Environment',
        difficulty: 'Medium',
      ),
      Word(
        id: '138',
        french: 'énergie',
        english: 'energy',
        category: 'Environment',
        difficulty: 'Medium',
      ),
      Word(
        id: '139',
        french: 'solaire',
        english: 'solar',
        category: 'Environment',
        difficulty: 'Hard',
      ),
      Word(
        id: '140',
        french: 'éolienne',
        english: 'wind turbine',
        category: 'Environment',
        difficulty: 'Hard',
      ),
      Word(
        id: '141',
        french: 'biodiversité',
        english: 'biodiversity',
        category: 'Environment',
        difficulty: 'Hard',
      ),
      Word(
        id: '142',
        french: 'écosystème',
        english: 'ecosystem',
        category: 'Environment',
        difficulty: 'Hard',
      ),
      Word(
        id: '143',
        french: 'océanographie',
        english: 'oceanography',
        category: 'Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '144',
        french: 'chimie',
        english: 'chemistry',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '145',
        french: 'physique',
        english: 'physics',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '146',
        french: 'biologie',
        english: 'biology',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '147',
        french: 'astronomie',
        english: 'astronomy',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '148',
        french: 'géologie',
        english: 'geology',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '149',
        french: 'mathématiques',
        english: 'mathematics',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '150',
        french: 'expérience',
        english: 'experiment',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '151',
        french: 'hypothèse',
        english: 'hypothesis',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '152',
        french: 'théorie',
        english: 'theory',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '153',
        french: 'modèle',
        english: 'model',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '154',
        french: 'loi',
        english: 'law',
        category: 'Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '155',
        french: 'calcul',
        english: 'calculation',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '156',
        french: 'addition',
        english: 'addition',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '157',
        french: 'soustraction',
        english: 'subtraction',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '158',
        french: 'multiplication',
        english: 'multiplication',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '159',
        french: 'division',
        english: 'division',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '160',
        french: 'fraction',
        english: 'fraction',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '161',
        french: 'pourcentage',
        english: 'percentage',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '162',
        french: 'racine carrée',
        english: 'square root',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '163',
        french: 'exposant',
        english: 'exponent',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '164',
        french: 'calculatrice',
        english: 'calculator',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '165',
        french: 'équation',
        english: 'equation',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '166',
        french: 'variables',
        english: 'variables',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '167',
        french: 'pi',
        english: 'pi',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '168',
        french: 'aire',
        english: 'area',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '169',
        french: 'volume',
        english: 'volume',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '170',
        french: 'cercle',
        english: 'circle',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '171',
        french: 'carré',
        english: 'square',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '172',
        french: 'triangle',
        english: 'triangle',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '173',
        french: 'rectangle',
        english: 'rectangle',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '174',
        french: 'trapèze',
        english: 'trapezoid',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '175',
        french: 'parallélogramme',
        english: 'parallelogram',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '176',
        french: 'pentagone',
        english: 'pentagon',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '177',
        french: 'hexagone',
        english: 'hexagon',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '178',
        french: 'heptagone',
        english: 'heptagon',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '179',
        french: 'octogone',
        english: 'octagon',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '180',
        french: 'dodecagone',
        english: 'dodecagon',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '181',
        french: 'symétrie',
        english: 'symmetry',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '182',
        french: 'asymétrie',
        english: 'asymmetry',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '183',
        french: 'coordonnées',
        english: 'coordinates',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '184',
        french: 'angle',
        english: 'angle',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '185',
        french: 'acutangle',
        english: 'acute angle',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '186',
        french: 'angle droit',
        english: 'right angle',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '187',
        french: 'angle obtus',
        english: 'obtuse angle',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '188',
        french: 'angle aigu',
        english: 'acute angle',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '189',
        french: 'périmètre',
        english: 'perimeter',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '190',
        french: 'diamètre',
        english: 'diameter',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '191',
        french: 'rayon',
        english: 'radius',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '192',
        french: 'circonférence',
        english: 'circumference',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '193',
        french: 'modèle mathématique',
        english: 'mathematical model',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '194',
        french: 'trigonométrie',
        english: 'trigonometry',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '195',
        french: 'géométrie',
        english: 'geometry',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '196',
        french: 'algèbre',
        english: 'algebra',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '197',
        french: 'arithmétique',
        english: 'arithmetic',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '198',
        french: 'statistiques',
        english: 'statistics',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '199',
        french: 'probabilité',
        english: 'probability',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '200',
        french: 'théorème',
        english: 'theorem',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '201',
        french: 'postulat',
        english: 'postulate',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '202',
        french: 'axiome',
        english: 'axiom',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '203',
        french: 'problème',
        english: 'problem',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '204',
        french: 'solution',
        english: 'solution',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '205',
        french: 'réponse',
        english: 'answer',
        category: 'Math',
        difficulty: 'Easy',
      ),
      Word(
        id: '206',
        french: 'inconnue',
        english: 'unknown',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '207',
        french: 'équation linéaire',
        english: 'linear equation',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '208',
        french: 'système d\'équations',
        english: 'system of equations',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '209',
        french: 'fonction',
        english: 'function',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '210',
        french: 'fonction linéaire',
        english: 'linear function',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '211',
        french: 'fonction quadratique',
        english: 'quadratic function',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '212',
        french: 'parabole',
        english: 'parabola',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '213',
        french: 'symétrie axiale',
        english: 'axial symmetry',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '214',
        french: 'symétrie centrale',
        english: 'central symmetry',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '215',
        french: 'fonction exponentielle',
        english: 'exponential function',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '216',
        french: 'fonction logarithmique',
        english: 'logarithmic function',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '217',
        french: 'limite',
        english: 'limit',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '218',
        french: 'dérivée',
        english: 'derivative',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '219',
        french: 'intégrale',
        english: 'integral',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '220',
        french: 'série',
        english: 'series',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '221',
        french: 'séquence',
        english: 'sequence',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '222',
        french: 'tangente',
        english: 'tangent',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '223',
        french: 'secante',
        english: 'secant',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '224',
        french: 'cosinus',
        english: 'cosine',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '225',
        french: 'sinus',
        english: 'sine',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '226',
        french: 'cotangente',
        english: 'cotangent',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '227',
        french: 'cosecante',
        english: 'cosecant',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '228',
        french: 'nombre premier',
        english: 'prime number',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '229',
        french: 'diviseur',
        english: 'divisor',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '230',
        french: 'multiplicité',
        english: 'multiplicity',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '231',
        french: 'factorisation',
        english: 'factorization',
        category: 'Math',
        difficulty: 'Medium',
      ),
      Word(
        id: '232',
        french: 'théorie des ensembles',
        english: 'set theory',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '233',
        french: 'graphe',
        english: 'graph',
        category: 'Math',
        difficulty: 'Hard',
      ),
      Word(
        id: '234',
        french: 'algorithme',
        english: 'algorithm',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '235',
        french: 'programmation',
        english: 'programming',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '236',
        french: 'compilateur',
        english: 'compiler',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '237',
        french: 'interpréteur',
        english: 'interpreter',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '238',
        french: 'débogage',
        english: 'debugging',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '239',
        french: 'binaire',
        english: 'binary',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '240',
        french: 'codage',
        english: 'coding',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '241',
        french: 'algorithme de tri',
        english: 'sorting algorithm',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '242',
        french: 'arbre binaire',
        english: 'binary tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '243',
        french: 'recherche',
        english: 'search',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '244',
        french: 'intelligence artificielle',
        english: 'artificial intelligence',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '245',
        french: 'machine learning',
        english: 'machine learning',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '246',
        french: 'réseau de neurones',
        english: 'neural network',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '247',
        french: 'réseaux informatiques',
        english: 'computer networks',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '248',
        french: 'cryptographie',
        english: 'cryptography',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '249',
        french: 'sécurité informatique',
        english: 'computer security',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '250',
        french: 'base de données',
        english: 'database',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '251',
        french: 'système de gestion de base de données',
        english: 'DBMS',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '252',
        french: 'requête SQL',
        english: 'SQL query',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '253',
        french: 'normalisation',
        english: 'normalization',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '254',
        french: 'index',
        english: 'index',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '255',
        french: 'transaction',
        english: 'transaction',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '256',
        french: 'redondance',
        english: 'redundancy',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '257',
        french: 'enregistrement',
        english: 'record',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '258',
        french: 'relation',
        english: 'relation',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '259',
        french: 'jointure',
        english: 'join',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '260',
        french: 'vue',
        english: 'view',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '261',
        french: 'normalisation des données',
        english: 'data normalization',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '262',
        french: 'sécurité des données',
        english: 'data security',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '263',
        french: 'stockage',
        english: 'storage',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '264',
        french: 'cloud computing',
        english: 'cloud computing',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '265',
        french: 'virtualisation',
        english: 'virtualization',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '266',
        french: 'serveur',
        english: 'server',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '267',
        french: 'client',
        english: 'client',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '268',
        french: 'API',
        english: 'API',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '269',
        french: 'REST',
        english: 'REST',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '270',
        french: 'JSON',
        english: 'JSON',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '271',
        french: 'environnement de développement',
        english: 'development environment',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '272',
        french: 'IDE',
        english: 'IDE',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '273',
        french: 'framework',
        english: 'framework',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '274',
        french: 'bibliothèque',
        english: 'library',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '275',
        french: 'test unitaire',
        english: 'unit test',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '276',
        french: 'tests automatisés',
        english: 'automated tests',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '277',
        french: 'intégration continue',
        english: 'continuous integration',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '278',
        french: 'déploiement continu',
        english: 'continuous deployment',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '279',
        french: 'containerisation',
        english: 'containerization',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '280',
        french: 'docker',
        english: 'docker',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '281',
        french: 'kubernetes',
        english: 'kubernetes',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '282',
        french: 'réseau local',
        english: 'local network',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '283',
        french: 'réseau étendu',
        english: 'wide area network',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '284',
        french: 'adresse IP',
        english: 'IP address',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '285',
        french: 'protocole',
        english: 'protocol',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '286',
        french: 'HTTP',
        english: 'HTTP',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '287',
        french: 'HTTPS',
        english: 'HTTPS',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '288',
        french: 'DNS',
        english: 'DNS',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '289',
        french: 'serveur proxy',
        english: 'proxy server',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '290',
        french: 'pare-feu',
        english: 'firewall',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '291',
        french: 'cryptage',
        english: 'encryption',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '292',
        french: 'décryptage',
        english: 'decryption',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '293',
        french: 'authentification',
        english: 'authentication',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '294',
        french: 'autorisations',
        english: 'permissions',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '295',
        french: 'gestion des utilisateurs',
        english: 'user management',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '296',
        french: 'gestion des sessions',
        english: 'session management',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '297',
        french: 'token',
        english: 'token',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '298',
        french: 'mots de passe',
        english: 'passwords',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '299',
        french: 'hashage',
        english: 'hashing',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '300',
        french: 'salage',
        english: 'salting',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '301',
        french: 'compression',
        english: 'compression',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '302',
        french: 'algorithme',
        english: 'algorithm',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '303',
        french: 'complexité algorithmique',
        english: 'algorithmic complexity',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '304',
        french: 'tri',
        english: 'sorting',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '305',
        french: 'recherche',
        english: 'searching',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '306',
        french: 'recherche binaire',
        english: 'binary search',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '307',
        french: 'tri à bulles',
        english: 'bubble sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '308',
        french: 'tri rapide',
        english: 'quick sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '309',
        french: 'tri par insertion',
        english: 'insertion sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '310',
        french: 'tri fusion',
        english: 'merge sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '311',
        french: 'structure de données',
        english: 'data structure',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '312',
        french: 'tableau',
        english: 'array',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '313',
        french: 'pile',
        english: 'stack',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '314',
        french: 'file',
        english: 'queue',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '315',
        french: 'liste chaînée',
        english: 'linked list',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '316',
        french: 'arbre binaire',
        english: 'binary tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '317',
        french: 'arbre AVL',
        english: 'AVL tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '318',
        french: 'arbre rouge-noir',
        english: 'red-black tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '319',
        french: 'graphe',
        english: 'graph',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '320',
        french: 'dijkstra',
        english: 'Dijkstra',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '321',
        french: 'algorithme de Bellman-Ford',
        english: 'Bellman-Ford algorithm',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '322',
        french: 'programme dynamique',
        english: 'dynamic programming',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '323',
        french: 'mémoire cache',
        english: 'cache memory',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '324',
        french: 'système d’exploitation',
        english: 'operating system',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '325',
        french: 'noyau',
        english: 'kernel',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '326',
        french: 'processus',
        english: 'process',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '327',
        french: 'thread',
        english: 'thread',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '328',
        french: 'gestion de la mémoire',
        english: 'memory management',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '329',
        french: 'partitionnement',
        english: 'partitioning',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '330',
        french: 'planification des processus',
        english: 'process scheduling',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '331',
        french: 'mutex',
        english: 'mutex',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '332',
        french: 'semaphore',
        english: 'semaphore',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '333',
        french: 'verrouillage',
        english: 'locking',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '334',
        french: 'système de fichiers',
        english: 'file system',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '335',
        french: 'mémoire virtuelle',
        english: 'virtual memory',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '336',
        french: 'pagination',
        english: 'paging',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '337',
        french: 'segmentation',
        english: 'segmentation',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '338',
        french: 'zombie',
        english: 'zombie',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '339',
        french: 'déférencement',
        english: 'dereferencing',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '340',
        french: 'pointer',
        english: 'pointer',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '341',
        french: 'allocation dynamique',
        english: 'dynamic allocation',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '342',
        french: 'garbage collection',
        english: 'garbage collection',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '343',
        french: 'interopérabilité',
        english: 'interoperability',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '344',
        french: 'portabilité',
        english: 'portability',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '345',
        french: 'compilateur',
        english: 'compiler',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '346',
        french: 'interpréteur',
        english: 'interpreter',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '347',
        french: 'langage de programmation',
        english: 'programming language',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '348',
        french: 'Python',
        english: 'Python',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '349',
        french: 'JavaScript',
        english: 'JavaScript',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '350',
        french: 'Java',
        english: 'Java',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '351',
        french: 'C++',
        english: 'C++',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '352',
        french: 'Ruby',
        english: 'Ruby',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '353',
        french: 'PHP',
        english: 'PHP',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '354',
        french: 'Go',
        english: 'Go',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '355',
        french: 'Rust',
        english: 'Rust',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '356',
        french: 'Swift',
        english: 'Swift',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '357',
        french: 'Kotlin',
        english: 'Kotlin',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '358',
        french: 'Scala',
        english: 'Scala',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '359',
        french: 'Perl',
        english: 'Perl',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '360',
        french: 'Lua',
        english: 'Lua',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '361',
        french: 'R',
        english: 'R',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '362',
        french: 'SQL',
        english: 'SQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '363',
        french: 'NoSQL',
        english: 'NoSQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '364',
        french: 'MongoDB',
        english: 'MongoDB',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '365',
        french: 'Firebase',
        english: 'Firebase',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '366',
        french: 'SQLite',
        english: 'SQLite',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '367',
        french: 'MySQL',
        english: 'MySQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '368',
        french: 'PostgreSQL',
        english: 'PostgreSQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '369',
        french: 'Oracle',
        english: 'Oracle',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '370',
        french: 'GraphQL',
        english: 'GraphQL',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '371',
        french: 'REST API',
        english: 'REST API',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '372',
        french: 'SOAP',
        english: 'SOAP',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '373',
        french: 'WebSocket',
        english: 'WebSocket',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '374',
        french: 'JSON',
        english: 'JSON',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '375',
        french: 'XML',
        english: 'XML',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '376',
        french: 'YAML',
        english: 'YAML',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '377',
        french: 'HTML',
        english: 'HTML',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '378',
        french: 'CSS',
        english: 'CSS',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '379',
        french: 'JavaScript DOM',
        english: 'JavaScript DOM',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '380',
        french: 'TypeScript',
        english: 'TypeScript',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '381',
        french: 'Angular',
        english: 'Angular',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '382',
        french: 'React',
        english: 'React',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '383',
        french: 'Vue.js',
        english: 'Vue.js',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '384',
        french: 'Svelte',
        english: 'Svelte',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '385',
        french: 'Node.js',
        english: 'Node.js',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '386',
        french: 'Express.js',
        english: 'Express.js',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '387',
        french: 'GraphQL API',
        english: 'GraphQL API',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '388',
        french: 'Flutter',
        english: 'Flutter',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '389',
        french: 'Dart',
        english: 'Dart',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '390',
        french: 'Xamarin',
        english: 'Xamarin',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '391',
        french: 'SwiftUI',
        english: 'SwiftUI',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '392',
        french: 'Jetpack Compose',
        english: 'Jetpack Compose',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '393',
        french: 'React Native',
        english: 'React Native',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '394',
        french: 'Ionic',
        english: 'Ionic',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '395',
        french: 'Cordova',
        english: 'Cordova',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '396',
        french: 'WebView',
        english: 'WebView',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '397',
        french: 'GraphQL mutation',
        english: 'GraphQL mutation',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '398',
        french: 'web scraping',
        english: 'web scraping',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '399',
        french: 'SEO',
        english: 'SEO',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '400',
        french: 'algorithmie',
        english: 'algorithmics',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '401',
        french: 'structure de données',
        english: 'data structure',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '402',
        french: 'tri rapide',
        english: 'quick sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '403',
        french: 'tri fusion',
        english: 'merge sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '404',
        french: 'tri par insertion',
        english: 'insertion sort',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '405',
        french: 'tri par sélection',
        english: 'selection sort',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '406',
        french: 'tri à bulles',
        english: 'bubble sort',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '407',
        french: 'algorithmie dynamique',
        english: 'dynamic programming',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '408',
        french: 'recherche binaire',
        english: 'binary search',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '409',
        french: 'recherche linéaire',
        english: 'linear search',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '410',
        french: 'graphes',
        english: 'graphs',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '411',
        french: 'DFS',
        english: 'DFS (Depth First Search)',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '412',
        french: 'BFS',
        english: 'BFS (Breadth First Search)',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '413',
        french: 'dijkstra',
        english: 'dijkstra',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '414',
        french: 'algorithmes gloutons',
        english: 'greedy algorithms',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '415',
        french: 'tri topologique',
        english: 'topological sort',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '416',
        french: 'arbre binaire',
        english: 'binary tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '417',
        french: 'arbre AVL',
        english: 'AVL tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '418',
        french: 'arbre rouge-noir',
        english: 'red-black tree',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '419',
        french: 'arbres de décision',
        english: 'decision trees',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '420',
        french: 'arbres binaires de recherche',
        english: 'binary search trees',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '421',
        french: 'hashage',
        english: 'hashing',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '422',
        french: 'table de hachage',
        english: 'hash table',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '423',
        french: 'filtrage collaboratif',
        english: 'collaborative filtering',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '424',
        french: 'apprentissage supervisé',
        english: 'supervised learning',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '425',
        french: 'apprentissage non supervisé',
        english: 'unsupervised learning',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '426',
        french: 'réseaux de neurones',
        english: 'neural networks',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '427',
        french: 'régression linéaire',
        english: 'linear regression',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '428',
        french: 'régression logistique',
        english: 'logistic regression',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '429',
        french: 'SVM',
        english: 'SVM (Support Vector Machine)',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '430',
        french: 'algorithmes génétiques',
        english: 'genetic algorithms',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '431',
        french: 'k-plus proches voisins',
        english: 'k-nearest neighbors',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '432',
        french: 'clustering',
        english: 'clustering',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '433',
        french: 'K-means',
        english: 'K-means',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '434',
        french: 'réseau de neurones convolutifs',
        english: 'convolutional neural network',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '435',
        french: 'réseau de neurones récurrents',
        english: 'recurrent neural network',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '436',
        french: 'algorithmes de recherche',
        english: 'search algorithms',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '437',
        french: 'intelligence artificielle',
        english: 'artificial intelligence',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '438',
        french: 'machine learning',
        english: 'machine learning',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '439',
        french: 'deep learning',
        english: 'deep learning',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '440',
        french: 'lien hypertexte',
        english: 'hyperlink',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '441',
        french: 'balise HTML',
        english: 'HTML tag',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '442',
        french: 'web dynamique',
        english: 'dynamic web',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '443',
        french: 'framework',
        english: 'framework',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '444',
        french: 'bibliothèque',
        english: 'library',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '445',
        french: 'fonctionnalité',
        english: 'feature',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '446',
        french: 'architecture logicielle',
        english: 'software architecture',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '447',
        french: 'microservices',
        english: 'microservices',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '448',
        french: 'conteneurisation',
        english: 'containerization',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '449',
        french: 'Docker',
        english: 'Docker',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '450',
        french: 'Kubernetes',
        english: 'Kubernetes',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '451',
        french: 'serveur web',
        english: 'web server',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '452',
        french: 'HTTP',
        english: 'HTTP (Hypertext Transfer Protocol)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '453',
        french: 'HTTPS',
        english: 'HTTPS (Hypertext Transfer Protocol Secure)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '454',
        french: 'REST',
        english: 'REST (Representational State Transfer)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '455',
        french: 'API',
        english: 'API (Application Programming Interface)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '456',
        french: 'JSON',
        english: 'JSON (JavaScript Object Notation)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '457',
        french: 'XML',
        english: 'XML (Extensible Markup Language)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '458',
        french: 'AJAX',
        english: 'AJAX (Asynchronous JavaScript and XML)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '459',
        french: 'WebSocket',
        english: 'WebSocket',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '460',
        french: 'JSON Web Token',
        english: 'JWT (JSON Web Token)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '461',
        french: 'OAuth',
        english: 'OAuth',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '462',
        french: 'authentification',
        english: 'authentication',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '463',
        french: 'autorisation',
        english: 'authorization',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '464',
        french: 'sécurisation des API',
        english: 'API security',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '465',
        french: 'SQL',
        english: 'SQL (Structured Query Language)',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '466',
        french: 'requête SQL',
        english: 'SQL query',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '467',
        french: 'base de données relationnelle',
        english: 'relational database',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '468',
        french: 'base de données NoSQL',
        english: 'NoSQL database',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '469',
        french: 'MongoDB',
        english: 'MongoDB',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '470',
        french: 'PostgreSQL',
        english: 'PostgreSQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '471',
        french: 'MySQL',
        english: 'MySQL',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '472',
        french: 'SQLite',
        english: 'SQLite',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '473',
        french: 'Oracle',
        english: 'Oracle',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '474',
        french: 'MongoDB Atlas',
        english: 'MongoDB Atlas',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '475',
        french: 'Cloud Computing',
        english: 'Cloud Computing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '476',
        french: 'AWS',
        english: 'AWS (Amazon Web Services)',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '477',
        french: 'Azure',
        english: 'Azure',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '478',
        french: 'Google Cloud',
        english: 'Google Cloud',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '479',
        french: 'serveur cloud',
        english: 'cloud server',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '480',
        french: 'stockage en nuage',
        english: 'cloud storage',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '481',
        french: 'Docker Compose',
        english: 'Docker Compose',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '482',
        french: 'CI/CD',
        english: 'CI/CD (Continuous Integration/Continuous Deployment)',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '483',
        french: 'pipeline de déploiement',
        english: 'deployment pipeline',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '484',
        french: 'test unitaire',
        english: 'unit testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '485',
        french: 'test d\'intégration',
        english: 'integration testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '486',
        french: 'test de charge',
        english: 'load testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '487',
        french: 'test fonctionnel',
        english: 'functional testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '488',
        french: 'test de performance',
        english: 'performance testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '489',
        french: 'test de sécurité',
        english: 'security testing',
        category: 'Computer Science',
        difficulty: 'Hard',
      ),
      Word(
        id: '490',
        french: 'tests automatisés',
        english: 'automated testing',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '491',
        french: 'framework de test',
        english: 'testing framework',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '492',
        french: 'Jenkins',
        english: 'Jenkins',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '493',
        french: 'Git',
        english: 'Git',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '494',
        french: 'GitHub',
        english: 'GitHub',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '495',
        french: 'GitLab',
        english: 'GitLab',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '496',
        french: 'Bitbucket',
        english: 'Bitbucket',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '497',
        french: 'Branching',
        english: 'Branching',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '498',
        french: 'merge',
        english: 'merge',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '499',
        french: 'Pull request',
        english: 'Pull request',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
      Word(
        id: '500',
        french: 'clonage',
        english: 'cloning',
        category: 'Computer Science',
        difficulty: 'Medium',
      ),
    ];
    notifyListeners();
  }

  List<Word> _filterWords() {
    return _words.where((word) {
      if (_selectedCategory != 'All' && word.category != _selectedCategory) {
        return false;
      }
      if (_difficulty != 'All' && word.difficulty != _difficulty) {
        return false;
      }
      return true;
    }).toList();
  }

  void setCategory(String category) {
    _selectedCategory = category;
    notifyListeners();
  }

  void setDifficulty(String difficulty) {
    _difficulty = difficulty;
    notifyListeners();
  }
}
